security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    voot:
                        password: %password_voot%
                        roles: 'ROLE_VOOT'
        simplesaml:
            id: app.user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        voot:
            pattern: ^/voot
            anonymous: ~
            http_basic: ~
            provider: in_memory

        saml:
            pattern: ^/
            anonymous: true
            stateless: true
            simple_preauth:
                authenticator: simplesamlphp.authenticator
                provider: simplesaml
            logout:
                path:   /logout
                success_handler: simplesamlphp.logout_handler

    access_control:
        - { path: ^/voot, roles: ROLE_VOOT }
        - { path: ^/, roles: ROLE_USER }
